### PR TITLE
"Daniel Ogidan"

### PR DESCRIPTION
**Pull request by ogidaniel1**
My assigments from Wk2-4

### CODE REVIEW

**Comment by chibuikem-k** [comment]
Hey.. Did you use Git to create your pull request?? Your PR has conflicting issues and I can't merge it

**Comment by chibuikem-k** [comment]
You can consider creating a new PR. Just create the markdown files for Week1 - Week4 assessments. Then create a PR

**Comment by ogidaniel1** [comment]
The previous one was done with git, will the new one was done directly from
GitHub.

But I will do the needful based on your request.

**Comment by chibuikem-k** [comment]
I still have issues merging this PR.. I'd close it so that you can create a new one

**Pull request closed without merging**
